"""empty message

Revision ID: 75a8f555a10d
Revises: 8c93e06830ef
Create Date: 2023-08-24 15:22:22.627574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a8f555a10d'
down_revision = '8c93e06830ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('teams_pokemon_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pokemon', ['pokemon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teams_pokemon_id_fkey', 'user', ['pokemon_id'], ['id'])

    # ### end Alembic commands ###
