"""empty message

Revision ID: db71a6654943
Revises: daf000b3eeed
Create Date: 2023-08-23 19:51:54.113142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db71a6654943'
down_revision = 'daf000b3eeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('teams_pokemon_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['pokemon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teams_pokemon_id_fkey', 'pokemon', ['pokemon_id'], ['id'])

    # ### end Alembic commands ###
